"""Add m2m model constraint

Revision ID: ef443667ebad
Revises: 33f242d5c684
Create Date: 2025-05-18 01:33:06.275765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef443667ebad"
down_revision: Union[str, None] = "33f242d5c684"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_chat", "chats", ["id", "group_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_chat", "chats", type_="unique")
    # ### end Alembic commands ###
