"""indexes adding

Revision ID: 48aea12a7a7f
Revises: f6d42a072762
Create Date: 2025-05-20 17:48:41.626036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48aea12a7a7f"
down_revision: Union[str, None] = "f6d42a072762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_chat_group_id", "chats", ["group_id"], unique=False)
    op.create_index("ix_chat_type", "chats", ["type"], unique=False)
    op.create_index(
        "idx_group_creator", "groups", ["creator_id"], unique=False
    )
    op.create_index(
        "idx_message_posted", "messages", ["timestamp"], unique=False
    )
    op.create_index(
        "idx_message_read_status", "messages", ["is_fully_read"], unique=False
    )
    op.create_index(
        "idx_message_sender_timestamp",
        "messages",
        ["sender_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_users_groups_composite",
        "users_groups",
        ["user_id", "group_id"],
        unique=False,
    )
    op.create_index(
        "idx_users_groups_group", "users_groups", ["group_id"], unique=False
    )
    op.create_index(
        "idx_users_groups_user", "users_groups", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_groups_user", table_name="users_groups")
    op.drop_index("idx_users_groups_group", table_name="users_groups")
    op.drop_index("idx_users_groups_composite", table_name="users_groups")
    op.drop_index("idx_message_sender_timestamp", table_name="messages")
    op.drop_index("idx_message_read_status", table_name="messages")
    op.drop_index("idx_message_posted", table_name="messages")
    op.drop_index("idx_group_creator", table_name="groups")
    op.drop_index("ix_chat_type", table_name="chats")
    op.drop_index("ix_chat_group_id", table_name="chats")
    # ### end Alembic commands ###
