"""Add ReadMessageStatus table

Revision ID: 529e42e5a46e
Revises: 8dcf40ba4003
Create Date: 2025-05-16 14:51:04.686721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "529e42e5a46e"
down_revision: Union[str, None] = "8dcf40ba4003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_read_statuses",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_read_statuses_message_id_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_message_read_statuses_recipient_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "message_id",
            "recipient_id",
            "id",
            name=op.f("pk_message_read_statuses"),
        ),
    )
    op.create_index(
        "ix_message_user",
        "message_read_statuses",
        ["message_id", "recipient_id"],
        unique=False,
    )
    op.create_index(
        "ix_read_status", "message_read_statuses", ["is_read"], unique=False
    )
    op.drop_column("messages", "read_mark")
    op.create_unique_constraint(
        "users_groups_unique", "users_groups", ["user_id", "group_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_groups_unique", "users_groups", type_="unique")
    op.add_column(
        "messages",
        sa.Column(
            "read_mark", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index("ix_read_status", table_name="message_read_statuses")
    op.drop_index("ix_message_user", table_name="message_read_statuses")
    op.drop_table("message_read_statuses")
    # ### end Alembic commands ###
