"""Table orphan fixes

Revision ID: f6d42a072762
Revises: 9ec1937ed99d
Create Date: 2025-05-18 01:53:30.010446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6d42a072762"
down_revision: Union[str, None] = "9ec1937ed99d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_message_read_statuses_message_id_messages",
        "message_read_statuses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_message_read_statuses_message_id_messages"),
        "message_read_statuses",
        "messages",
        ["message_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_message_read_statuses_message_id_messages"),
        "message_read_statuses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_message_read_statuses_message_id_messages",
        "message_read_statuses",
        "messages",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
