"""Add cascade deletes

Revision ID: 9ec1937ed99d
Revises: ef443667ebad
Create Date: 2025-05-18 01:43:34.231651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ec1937ed99d"
down_revision: Union[str, None] = "ef443667ebad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_chat_id_chats', 'messages', type_='foreignkey')
    op.drop_constraint('fk_message_read_statuses_message_id_messages', 'message_read_statuses', type_='foreignkey')

    # Создаем новые с ON DELETE CASCADE
    op.create_foreign_key(
        'fk_messages_chat_id_chats',
        'messages', 'chats',
        ['chat_id'], ['id'],
        ondelete='CASCADE'
    )

    op.create_foreign_key(
        'fk_message_read_statuses_message_id_messages',
        'message_read_statuses', 'messages',
        ['message_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_chat_id_chats', 'messages', type_='foreignkey')
    op.drop_constraint('fk_message_read_statuses_message_id_messages', 'message_read_statuses', type_='foreignkey')

    op.create_foreign_key(
        'fk_messages_chat_id_chats',
        'messages', 'chats',
        ['chat_id'], ['id']
    )

    op.create_foreign_key(
        'fk_message_read_statuses_message_id_messages',
        'message_read_statuses', 'messages',
        ['message_id'], ['id']
    )
    # ### end Alembic commands ###
